/* DO NOT EDIT THIS FILE - it is machine generated */
//package com.example.textureviewwithopengles;
#include <jni.h>
/* Header for class com_example_project1_RenderCode */

#ifndef _Included_com_example_textureviewwithopengles_RenderCode
#define _Included_com_example_textureviewwithopengles_RenderCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_project1_RenderCode
 * Method:    InitGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_textureviewwithopengles_RenderCode_InitGL
  (JNIEnv *, jclass);

/*
 * Class:     com_example_project1_RenderCode
 * Method:    ResizeGL
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_textureviewwithopengles_RenderCode_ResizeGL
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_project1_RenderCode
 * Method:    PaintGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_textureviewwithopengles_RenderCode_PaintGL
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
